### ISSUE TITLE
poor evalulation result 

### ISSUE THREAD

**Issue by qzhai** [aysim/comingdowntoearth#1]
Hi,

I test the CVUSA benchmark using the released model but get very pool accuracy,
Recall(p2s/s2p) tp1:0.20/0.10 tp5:0.63/0.50 tp10:1.15/0.90 tp1%:5.12/4.45
what's wrong with the model?

**Comment by qzhai** [comment]
> Hi,
> 
> I test the CVUSA benchmark using the released model but get very pool accuracy, Recall(p2s/s2p) tp1:0.20/0.10 tp5:0.63/0.50 tp10:1.15/0.90 tp1%:5.12/4.45 what's wrong with the model?

Hi,

I test the model on the images after the polar transform, the performance is normal but still worse than the paper. Now I get the result: Recall(p2s/s2p) tp1:84.69/84.73 tp5:94.37/94.41 tp10:96.36/96.26 tp1%:99.05/98.82,
the result in the paper is recall1: 92.56, recall5: 97.55, recall10: 98.33, top1%: 99.57

**Comment by aysim** [comment]
Hey, 

Thanks for your comment! I had a look at the data preparation script and realised that there was actually a small discrepancy: The polar transformation was computed on the resolution 224x1232 (double resolution). I updated the code according to that. Please run data/convert_polar.py to apply polar transformation on satellite images. Then run the test script.

However, I have to say that the results only change slightly between these two settings, nowhere near the numbers you mention. Anyways, the code now reproduces the numbers from the paper exactly. Below are the 
numbers I got:
<img width="653" alt="Screenshot 2022-01-17 at 15 48 01" src="https://user-images.githubusercontent.com/11741574/149818723-8af0281d-034e-41a5-9e73-c72a938652d7.png">

**Comment by steven30currry** [comment]
Hello, author. Could you please provide the code of ssim, psnr and sd? I used other codes to test, and found that the effect was poor. In addition, can you upload this best checkpoint, thank you very much, just for academic research

> Hey,
> 
> Thanks for your comment! I had a look at the data preparation script and realised that there was actually a small discrepancy: The polar transformation was computed on the resolution 224x1232 (double resolution). I updated the code according to that. Please run data/convert_polar.py to apply polar transformation on satellite images. Then run the test script.
> 
> However, I have to say that the results only change slightly between these two settings, nowhere near the numbers you mention. Anyways, the code now reproduces the numbers from the paper exactly. Below are the numbers I got: <img alt="Screenshot 2022-01-17 at 15 48 01" width="653" src="https://user-images.githubusercontent.com/11741574/149818723-8af0281d-034e-41a5-9e73-c72a938652d7.png">

**Comment by steven30currry** [comment]
> Hey,
> 
> Thanks for your comment! I had a look at the data preparation script and realised that there was actually a small discrepancy: The polar transformation was computed on the resolution 224x1232 (double resolution). I updated the code according to that. Please run data/convert_polar.py to apply polar transformation on satellite images. Then run the test script.
> 
> However, I have to say that the results only change slightly between these two settings, nowhere near the numbers you mention. Anyways, the code now reproduces the numbers from the paper exactly. Below are the numbers I got: <img alt="Screenshot 2022-01-17 at 15 48 01" width="653" src="https://user-images.githubusercontent.com/11741574/149818723-8af0281d-034e-41a5-9e73-c72a938652d7.png">

![image](https://github.com/aysim/comingdowntoearth/assets/58033787/495ee210-6ca5-4826-bae8-e1c78b9dfccd)
This is the best training metric I've gotten with your code so far, and it's still far from the paper
